/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/atmIframe.glb -o src/Model.jsx -r public 
*/

import React from "react"
import { useGLTF } from "@react-three/drei"

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/atmIframe.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.atmIframe.geometry}
        material={nodes.atmIframe.material}
        position={[1.675, 1.185, 0.858]}
        rotation={[1.47, 0.194, -1.088]}
      />
    </group>
  )
}

useGLTF.preload("/models/atmIframe.glb")
