/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/project6/Castle.glb -o src/components/Model.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/project6/Castle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.castleUV_Baked.geometry} material={nodes.castleUV_Baked.material} />
    </group>
  )
}

useGLTF.preload('/models/project6/Castle.glb')
