/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/OrbitV2.glb -o src/Model.jsx -r public 
*/

import React from "react"
import { useGLTF } from "@react-three/drei"

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/OrbitV2.glb")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lineC.geometry} material={nodes.lineC.material} />
      <mesh geometry={nodes.lineB.geometry} material={nodes.lineB.material} />
      <mesh geometry={nodes.lineA.geometry} material={nodes.lineA.material} />
      <mesh geometry={nodes.center.geometry} material={nodes.center.material} />
      <mesh geometry={nodes.ballC.geometry} material={nodes.ballC.material} />
      <mesh
        geometry={nodes.ballA.geometry}
        material={nodes.ballA.material}
        scale={0.993}
      />
      <mesh
        geometry={nodes.ballB.geometry}
        material={nodes.ballB.material}
        scale={1.125}
      />
    </group>
  )
}

useGLTF.preload("/models/OrbitV2.glb")
