/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Flower.glb -o src/Model.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/Flower.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.flowers.geometry} material={nodes.flowers.material} position={[0, 2.777, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/Flower.glb')
